'use strict'

const PouchDB = require('pouchdb')
const couchPass = require('./couchPass.json')
const faunaById = require('./views/faunaById.js')
const fieldsOfGroup = require('./views/fieldsOfGroup.js')
const floraById = require('./views/floraById.js')
const groups = require('./views/groups.js')
const artendb = require('./views/artendb.js')
const macromycetesById = require('./views/macromycetesById.js')
const mooseById = require('./views/mooseById.js')
const objects = require('./views/objects.js')
const objectsIdsByPcsName = require('./views/objectsIdsByPcsName.js')
const objectsIdsByRcsName = require('./views/objectsIdsByRcsName.js')
const organizations = require('./views/organizations.js')
const pcs = require('./views/pcs.js')
const rcs = require('./views/rcs.js')
const taxonomies = require('./views/taxonomies.js')
const taxonomyObjects = require('./views/taxonomyObjects.js')
const tcs = require('./views/tcs.js')
const groupFilter = require('./filters/groupFilter.js')

const couchUrl = `http://${couchPass.user}:${couchPass.pass}@127.0.0.1:5984/artendb`
// const couchUrl = `http://${couchPass.user}:${couchPass.pass}@46.101.210.208:5984/artendb`

const db = new PouchDB(couchUrl)
artendb(db)
faunaById(db)
fieldsOfGroup(db)
floraById(db)
groups(db)
macromycetesById(db)
mooseById(db)
objects(db)
objectsIdsByPcsName(db)
objectsIdsByRcsName(db)
organizations(db)
pcs(db)
rcs(db)
taxonomies(db)
taxonomyObjects(db)
tcs(db)
groupFilter(db)
